config/routes.rb
RailsRemoteLogger::Application.routes.draw do
  root to: 'log#index'

  match 'log/:shost/search_by_host' => "log#search_by_host", as: :log_search_host
  match 'log/:stoken/search_by_token' => "log#search_by_token", as: :log_search_token

  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      match "log/create" => "log#create", via: :post
    end
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  validates :message, :host, :path, :useragent,  presence: true

  attr_accessible :message, :host, :path, :useragent, :token, :requested_ip
end

app/controllers/api/v1/log_controller.rb
module Api
  module V1
    class LogController < ApplicationController
      def create
        puts "IP: #{request.remote_ip}"
        log = Log.new(params[:log])
        log.requested_ip = request.remote_ip

        if log.save
          render json: { success: true }
        else
          render json: { success: false }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/log_controller.rb
class LogController < ApplicationController
  def index
    @logs = Log.all.uniq{ |l| l.host }
  end

  def search_by_token
    @logs = Log.find_all_by_token(params[:stoken])
  end

  def search_by_host
    @logs = Log.find_all_by_host(params[:shost])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsRemoteLogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/log/index.html.haml
%h2 Domains

%ul
  - @logs.each do |l|
    %li
      = link_to l.host, log_search_host_path(l.host)

app/views/log/search_by_host.html.haml
%h2
  Logs -
  = @logs.first.host

%table
  %thead
    %th host
    %th path
    %th useragent
    %th token
    %th requested ip
    %th message

  %tbody
    - @logs.each do |l|
      %tr
        %td
          = l.host
        %td
          = l.path
        %td
          = l.useragent
        %td
          = l.token
        %td
          = l.requested_ip
        %td
          = l.message

app/views/log/search_by_token.html.haml
%h2
  Logs -
  = @logs.first.token

%table
  %thead
    %th host
    %th path
    %th useragent
    %th token
    %th requested ip
    %th message

  %tbody
    - @logs.each do |l|
      %tr
        %td
          = l.host
        %td
          = l.path
        %td
          = l.useragent
        %td
          = link_to l.token, log_token_search_path(l.token)
        %td
          = l.requested_ip
        %td
          = l.message